import { AirbnbProperty } from './listings';

export const MOCK_PROPERTIES: AirbnbProperty[] = [
  {
    id: 'mock-1',
    name: 'Luxury Villa with Private Pool and Ocean View',
    picture_url: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80',
    price: 350, currency: 'USD', rating: 4.9, reviews_count: 128,
    room_type: 'Entire home', bedrooms: 4, beds: 5, bathrooms: 3,
    description: 'Experience ultimate luxury in this beautiful villa with a stunning infinity pool overlooking the ocean.',
    amenities: ['Pool', 'Wifi', 'Kitchen', 'Free parking', 'Air conditioning', 'Ocean view', 'BBQ grill'],
    location: { latitude: 34.0259, longitude: -118.4907, address: 'Malibu, California, United States' },
    host: { id: 'host-1', name: 'Sarah Anderson', picture_url: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&q=80' },
  },
  {
    id: 'mock-2',
    name: 'Cozy Downtown Loft with City Skyline Views',
    picture_url: 'https://images.unsplash.com/photo-1449844908441-8829872d2607?auto=format&fit=crop&q=80',
    price: 150, currency: 'USD', rating: 4.8, reviews_count: 245,
    room_type: 'Entire apartment', bedrooms: 1, beds: 1, bathrooms: 1,
    description: 'Stay in the heart of the city in this stylish modern loft with panoramic skyline views.',
    amenities: ['Wifi', 'Kitchen', 'Air conditioning', 'Gym', 'Elevator', 'Workspace'],
    location: { latitude: 40.7128, longitude: -74.0060, address: 'Downtown, New York, United States' },
    host: { id: 'host-2', name: 'Michael Chen', picture_url: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80' },
  },
  {
    id: 'mock-3',
    name: 'Serene Forest Cabin Hideaway',
    picture_url: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&q=80',
    price: 120, currency: 'USD', rating: 4.95, reviews_count: 89,
    room_type: 'Entire cabin', bedrooms: 2, beds: 3, bathrooms: 1,
    description: 'Disconnect in this A-frame cabin surrounded by pine trees with a cozy fireplace and outdoor hot tub.',
    amenities: ['Wifi', 'Kitchen', 'Indoor fireplace', 'Hot tub', 'Pets allowed', 'Mountain view'],
    location: { latitude: 39.5501, longitude: -105.7821, address: 'Breckenridge, Colorado, United States' },
    host: { id: 'host-3', name: 'Emily Davis', picture_url: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80' },
  },
  {
    id: 'mock-4',
    name: 'Modern Beachfront Guest House',
    picture_url: 'https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?auto=format&fit=crop&q=80',
    price: 220, currency: 'USD', rating: 4.75, reviews_count: 156,
    room_type: 'Entire guest house', bedrooms: 1, beds: 2, bathrooms: 1,
    description: 'Step right onto the sand from this renovated guest house. Wake up to waves and watch the sunset from your patio.',
    amenities: ['Wifi', 'Kitchen', 'Beachfront', 'Patio', 'Free parking', 'Air conditioning'],
    location: { latitude: 25.7617, longitude: -80.1918, address: 'Miami Beach, Florida, United States' },
    host: { id: 'host-4', name: 'Carlos Rodriguez', picture_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80' },
  },
  {
    id: 'mock-5',
    name: 'Charming Studio in the Arts District',
    picture_url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&q=80',
    price: 95, currency: 'USD', rating: 4.7, reviews_count: 312,
    room_type: 'Entire studio', bedrooms: 1, beds: 1, bathrooms: 1,
    description: 'A beautifully decorated studio with high ceilings, original hardwood floors, and curated local art.',
    amenities: ['Wifi', 'Kitchen', 'Air conditioning', 'Washer', 'Self check-in', 'Workspace'],
    location: { latitude: 34.0407, longitude: -118.2349, address: 'Arts District, Los Angeles, United States' },
    host: { id: 'host-5', name: 'Isabelle Martin', picture_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80' },
  },
  {
    id: 'mock-6',
    name: 'Stunning Penthouse with Rooftop Terrace',
    picture_url: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&q=80',
    price: 480, currency: 'USD', rating: 4.92, reviews_count: 74,
    room_type: 'Entire penthouse', bedrooms: 3, beds: 3, bathrooms: 2,
    description: 'A private rooftop terrace with 360° views, a gourmet kitchen, and designer furnishings throughout.',
    amenities: ['Pool', 'Wifi', 'Kitchen', 'Rooftop terrace', 'Air conditioning', 'Gym', 'Doorman'],
    location: { latitude: 41.8827, longitude: -87.6233, address: 'River North, Chicago, United States' },
    host: { id: 'host-6', name: 'James Whitfield', picture_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80' },
  },
  {
    id: 'mock-7',
    name: 'Rustic Desert Retreat with Hot Tub',
    picture_url: 'https://images.unsplash.com/photo-1518780664697-55e3ad937233?auto=format&fit=crop&q=80',
    price: 175, currency: 'USD', rating: 4.85, reviews_count: 203,
    room_type: 'Entire home', bedrooms: 2, beds: 2, bathrooms: 2,
    description: 'Floor-to-ceiling windows frame stunning red rock views. Private hot tub under the stars included.',
    amenities: ['Hot tub', 'Wifi', 'Kitchen', 'Free parking', 'Air conditioning', 'Desert view', 'BBQ grill'],
    location: { latitude: 33.7206, longitude: -111.9748, address: 'Scottsdale, Arizona, United States' },
    host: { id: 'host-7', name: 'Natalie Brooks', picture_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80' },
  },
  {
    id: 'mock-8',
    name: 'Historic Brownstone in Beacon Hill',
    picture_url: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&q=80',
    price: 210, currency: 'USD', rating: 4.78, reviews_count: 167,
    room_type: 'Entire apartment', bedrooms: 2, beds: 2, bathrooms: 1,
    description: "A beautifully restored 19th-century brownstone in one of Boston's most iconic neighborhoods.",
    amenities: ['Wifi', 'Kitchen', 'Washer', 'Dryer', 'Heating', 'Self check-in'],
    location: { latitude: 42.3588, longitude: -71.0707, address: 'Beacon Hill, Boston, United States' },
    host: { id: 'host-8', name: 'Thomas Harrington', picture_url: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80' },
  },
  {
    id: 'mock-9',
    name: 'Lakefront Cottage with Private Dock',
    picture_url: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&q=80',
    price: 195, currency: 'USD', rating: 4.88, reviews_count: 142,
    room_type: 'Entire cottage', bedrooms: 3, beds: 4, bathrooms: 2,
    description: 'A classic lakefront cottage with a private dock, kayaks, and paddleboards included.',
    amenities: ['Wifi', 'Kitchen', 'Lake access', 'Private dock', 'Kayaks', 'BBQ grill', 'Pets allowed'],
    location: { latitude: 44.9778, longitude: -93.2650, address: 'Lake Minnetonka, Minnesota, United States' },
    host: { id: 'host-9', name: 'Laura Jensen', picture_url: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?auto=format&fit=crop&q=80' },
  },
  {
    id: 'mock-10',
    name: 'Sleek Minimalist Condo in South Beach',
    picture_url: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&q=80',
    price: 260, currency: 'USD', rating: 4.72, reviews_count: 198,
    room_type: 'Entire condo', bedrooms: 2, beds: 2, bathrooms: 2,
    description: 'A sleek modern condo steps from the beach with rooftop pool and direct access to South Beach nightlife.',
    amenities: ['Pool', 'Wifi', 'Kitchen', 'Gym', 'Air conditioning', 'Balcony', 'Beach access'],
    location: { latitude: 25.7825, longitude: -80.1300, address: 'South Beach, Miami, United States' },
    host: { id: 'host-10', name: 'Diego Morales', picture_url: 'https://images.unsplash.com/photo-1463453091185-61582044d556?auto=format&fit=crop&q=80' },
  },
  {
    id: 'mock-11',
    name: 'Treehouse Escape in the Pacific Northwest',
    picture_url: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&q=80',
    price: 145, currency: 'USD', rating: 4.97, reviews_count: 61,
    room_type: 'Treehouse', bedrooms: 1, beds: 1, bathrooms: 1,
    description: 'A magical treehouse nestled among old-growth Douglas firs. Fall asleep to rain on the canopy.',
    amenities: ['Wifi', 'Kitchen', 'Heating', 'Self check-in', 'Forest view', 'Outdoor shower'],
    location: { latitude: 47.6062, longitude: -122.3321, address: 'Snoqualmie Valley, Washington, United States' },
    host: { id: 'host-11', name: 'Fiona Walsh', picture_url: 'https://images.unsplash.com/photo-1489424731084-a5d8b219a5bb?auto=format&fit=crop&q=80' },
  },
  {
    id: 'mock-12',
    name: 'Grand Victorian Mansion near Golden Gate',
    picture_url: 'https://images.unsplash.com/photo-1505843513577-22bb7d21e455?auto=format&fit=crop&q=80',
    price: 395, currency: 'USD', rating: 4.83, reviews_count: 110,
    room_type: 'Entire home', bedrooms: 5, beds: 6, bathrooms: 4,
    description: 'A meticulously restored Victorian mansion minutes from the Golden Gate Bridge with a lush private garden.',
    amenities: ['Wifi', 'Kitchen', 'Free parking', 'Garden', 'Fireplace', 'Washer', 'Dryer'],
    location: { latitude: 37.7749, longitude: -122.4194, address: 'Pacific Heights, San Francisco, United States' },
    host: { id: 'host-12', name: 'Robert Kim', picture_url: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&q=80' },
  },
  {
    id: 'mock-13',
    name: 'Bohemian Bungalow with Garden Oasis',
    picture_url: 'https://images.unsplash.com/photo-1510798831971-661eb04b3739?auto=format&fit=crop&q=80',
    price: 110, currency: 'USD', rating: 4.76, reviews_count: 184,
    room_type: 'Entire bungalow', bedrooms: 2, beds: 2, bathrooms: 1,
    description: 'A charming bohemian bungalow surrounded by a lush tropical garden. Perfect for a peaceful urban escape.',
    amenities: ['Wifi', 'Kitchen', 'Garden', 'Outdoor shower', 'Pets allowed', 'Self check-in'],
    location: { latitude: 30.2672, longitude: -97.7431, address: 'East Austin, Texas, United States' },
    host: { id: 'host-13', name: 'Maya Patel', picture_url: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&q=80' },
  },
  {
    id: 'mock-14',
    name: 'Ski-In Ski-Out Chalet in Aspen',
    picture_url: 'https://images.unsplash.com/photo-1548802673-380ab8ebc7b7?auto=format&fit=crop&q=80',
    price: 620, currency: 'USD', rating: 4.94, reviews_count: 47,
    room_type: 'Entire chalet', bedrooms: 4, beds: 6, bathrooms: 3,
    description: 'Wake up and ski straight from your door in this stunning alpine chalet. Stone fireplace, sauna, and mountain views.',
    amenities: ['Ski-in/Ski-out', 'Sauna', 'Fireplace', 'Wifi', 'Kitchen', 'Mountain view', 'Hot tub'],
    location: { latitude: 39.1911, longitude: -106.8175, address: 'Aspen, Colorado, United States' },
    host: { id: 'host-14', name: 'Henrik Larsson', picture_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80' },
  },
  {
    id: 'mock-15',
    name: 'Waterfront Houseboat on Lake Union',
    picture_url: 'https://images.unsplash.com/photo-1534430480872-3498386e7856?auto=format&fit=crop&q=80',
    price: 185, currency: 'USD', rating: 4.86, reviews_count: 93,
    room_type: 'Houseboat', bedrooms: 2, beds: 2, bathrooms: 1,
    description: 'Live on the water in this beautifully designed houseboat. Stunning lake views, kayaks included, steps from the city.',
    amenities: ['Wifi', 'Kitchen', 'Lake view', 'Kayaks', 'Deck', 'Air conditioning'],
    location: { latitude: 47.6501, longitude: -122.3321, address: 'Lake Union, Seattle, United States' },
    host: { id: 'host-15', name: 'Anna Kowalski', picture_url: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?auto=format&fit=crop&q=80' },
  },
  {
    id: 'mock-16',
    name: 'Elegant Townhouse in Georgetown',
    picture_url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&q=80',
    price: 290, currency: 'USD', rating: 4.81, reviews_count: 135,
    room_type: 'Entire townhouse', bedrooms: 3, beds: 3, bathrooms: 2,
    description: 'A beautifully appointed townhouse in the heart of historic Georgetown, steps from top restaurants and the waterfront.',
    amenities: ['Wifi', 'Kitchen', 'Washer', 'Dryer', 'Patio', 'Free parking', 'Air conditioning'],
    location: { latitude: 38.9076, longitude: -77.0723, address: 'Georgetown, Washington D.C., United States' },
    host: { id: 'host-16', name: 'Patricia Monroe', picture_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80' },
  },
  {
    id: 'mock-17',
    name: 'Converted Warehouse Loft in Brooklyn',
    picture_url: 'https://images.unsplash.com/photo-1536376072261-38c75010e6c9?auto=format&fit=crop&q=80',
    price: 165, currency: 'USD', rating: 4.73, reviews_count: 221,
    room_type: 'Entire loft', bedrooms: 1, beds: 2, bathrooms: 1,
    description: 'An industrial-chic loft in a converted warehouse with soaring ceilings, exposed brick, and a private rooftop.',
    amenities: ['Wifi', 'Kitchen', 'Rooftop access', 'Air conditioning', 'Workspace', 'Gym'],
    location: { latitude: 40.6782, longitude: -73.9442, address: 'Williamsburg, Brooklyn, United States' },
    host: { id: 'host-17', name: 'Jordan Lee', picture_url: 'https://images.unsplash.com/photo-1463453091185-61582044d556?auto=format&fit=crop&q=80' },
  },
  {
    id: 'mock-18',
    name: 'Cliffside Retreat with Infinity Pool',
    picture_url: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&q=80',
    price: 540, currency: 'USD', rating: 4.96, reviews_count: 38,
    room_type: 'Entire villa', bedrooms: 3, beds: 4, bathrooms: 3,
    description: 'Perched on a dramatic cliff with an infinity pool that seems to merge with the ocean horizon. Pure paradise.',
    amenities: ['Infinity pool', 'Wifi', 'Kitchen', 'Ocean view', 'BBQ grill', 'Air conditioning', 'Private chef available'],
    location: { latitude: 20.6534, longitude: -105.2253, address: 'Sayulita, Nayarit, Mexico' },
    host: { id: 'host-18', name: 'Sofia Reyes', picture_url: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&q=80' },
  },
  {
    id: 'mock-19',
    name: 'Cozy Mountain Farmhouse with Fireplace',
    picture_url: 'https://images.unsplash.com/photo-1542718610-a1d656d1884c?auto=format&fit=crop&q=80',
    price: 155, currency: 'USD', rating: 4.89, reviews_count: 76,
    room_type: 'Entire farmhouse', bedrooms: 3, beds: 4, bathrooms: 2,
    description: 'A lovingly restored farmhouse with original wood beams, a stone fireplace, and sweeping mountain meadow views.',
    amenities: ['Fireplace', 'Wifi', 'Kitchen', 'Free parking', 'Pets allowed', 'Mountain view', 'BBQ grill'],
    location: { latitude: 36.1070, longitude: -115.1728, address: 'Blue Ridge Mountains, Virginia, United States' },
    host: { id: 'host-19', name: 'William Foster', picture_url: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80' },
  },
  {
    id: 'mock-20',
    name: 'Luxury High-Rise Suite with Strip Views',
    picture_url: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?auto=format&fit=crop&q=80',
    price: 310, currency: 'USD', rating: 4.77, reviews_count: 259,
    room_type: 'Entire suite', bedrooms: 2, beds: 2, bathrooms: 2,
    description: 'Floor-to-ceiling windows showcase dazzling Strip views from this high-rise suite. Pool, spa, and casino downstairs.',
    amenities: ['Pool', 'Spa', 'Wifi', 'Kitchen', 'Gym', 'Air conditioning', 'Strip view', 'Concierge'],
    location: { latitude: 36.1147, longitude: -115.1728, address: 'The Strip, Las Vegas, United States' },
    host: { id: 'host-20', name: 'Victor Nguyen', picture_url: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&q=80' },
  },
];

// Each location shows a unique set of 20 properties (all of them, shuffled differently)
const PLACE_MOCK_MAP: Record<string, string[]> = {
  '1015254': ['mock-2', 'mock-8', 'mock-17', 'mock-6', 'mock-11', 'mock-15', 'mock-9', 'mock-16', 'mock-3', 'mock-13', 'mock-19', 'mock-5', 'mock-14', 'mock-1', 'mock-20', 'mock-7', 'mock-4', 'mock-10', 'mock-12', 'mock-18'],
  '1352823': ['mock-1', 'mock-5', 'mock-13', 'mock-7', 'mock-18', 'mock-10', 'mock-12', 'mock-3', 'mock-20', 'mock-4', 'mock-15', 'mock-17', 'mock-6', 'mock-2', 'mock-9', 'mock-14', 'mock-8', 'mock-11', 'mock-16', 'mock-19'],
  '1015252': ['mock-12', 'mock-15', 'mock-3', 'mock-6', 'mock-18', 'mock-1', 'mock-9', 'mock-11', 'mock-5', 'mock-20', 'mock-2', 'mock-14', 'mock-7', 'mock-13', 'mock-4', 'mock-17', 'mock-8', 'mock-16', 'mock-10', 'mock-19'],
  '1015253': ['mock-6', 'mock-2', 'mock-8', 'mock-14', 'mock-17', 'mock-4', 'mock-11', 'mock-19', 'mock-1', 'mock-15', 'mock-3', 'mock-20', 'mock-9', 'mock-5', 'mock-13', 'mock-12', 'mock-7', 'mock-10', 'mock-16', 'mock-18'],
  '1015255': ['mock-4', 'mock-10', 'mock-18', 'mock-1', 'mock-7', 'mock-5', 'mock-20', 'mock-13', 'mock-6', 'mock-2', 'mock-15', 'mock-3', 'mock-9', 'mock-17', 'mock-11', 'mock-8', 'mock-14', 'mock-12', 'mock-16', 'mock-19'],
  '1015256': ['mock-20', 'mock-7', 'mock-6', 'mock-10', 'mock-18', 'mock-3', 'mock-2', 'mock-14', 'mock-1', 'mock-5', 'mock-13', 'mock-15', 'mock-4', 'mock-9', 'mock-17', 'mock-11', 'mock-8', 'mock-12', 'mock-16', 'mock-19'],
};

export const getMockPropertiesForPlace = (placeId: string): AirbnbProperty[] => {
  const ids = PLACE_MOCK_MAP[placeId];
  if (!ids) return MOCK_PROPERTIES;
  return ids.map(id => MOCK_PROPERTIES.find(p => p.id === id)!).filter(Boolean);
};
